spring:
  application:
    name: order-service
  config:
    import:
      - optional:classpath:external/order_service.properties

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order-service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8081
