spring:
  application:
    name: order-service
  config:
    import:
      - optional:classpath:external/order_service.properties

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order-service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  #Kafka properties
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: order-placed
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        schema:
          registry:
            url: http://127.0.0.1:8085

management:
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: order-service
  tracing:
    sampling:
      probability: 1.0

server:
  port: 8081

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

inventory:
  url: http://localhost:8082

#Resilience4j properties
resilience4j:
  circuit-breaker:
    instances:
      inventory:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        minimum-number-of-calls: 5
  #Resilience4j Timeout properties
  timelimiter:
    instances:
      inventory:
        timeout-duration: 3s
  #Resilience4j Retry properties
  retry:
    instances:
      inventory:
        max-attempts: 3
        wait-duration: 5s

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka


