spring:
  application:
    name: inventory-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/inventory-service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8082

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#    enabled: true
#    register-with-eureka: true
#    fetch-registry: true