spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017/product-service?authSource=admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka