spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017/product-service?authSource=admin

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka